import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "Faceauth.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>{children}</body>
      <script src="/vendors/@popperjs/popper.min.js"></script>
      <script src="/vendors/bootstrap/bootstrap.min.js"></script>
      <script src="/vendors/is/is.min.js"></script>
      <script src="/vendors/fontawesome/all.min.js"></script>
      <script src="/assets/js/theme.js"></script>
    </html>
  );
}
